services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "https://example.com/win.iso"
      DISK_SIZE: "19G"
      RAM_SIZE: "10G"
      CPU_CORES: "4"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
    restart: always
    stop_grace_period: 2m
